---
title: "TRI Bayesiana"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ltm)
library(mirt)
library(irtoys)
```

## Dados

```{r, include = F}
#Respostas
data <- read_csv2("respostas.csv")
perguntas <- colnames(data)
colnames(data) <- c(paste0("i",1:13), paste0("f",1:3))

#Gabarito
gab <- read_csv2("gabarito.csv", col_names = FALSE)
colnames(gab) <- c(paste0("i",1:13))

#Desconsidera as linhas incompletas
data.NA <- data[complete.cases(data), ]

#Correção
data.f <- mult.choice(data.NA[,1:13],as.numeric(gab))
```

```{r}
head(data.f)
dim(data.f)

acertos <- table(rowSums(data.f))
barplot(acertos)

questoes <- colSums(data.f)
barplot(questoes)
```

## Análise original

### Mirt

```{r}
mirt.2PL <- mirt(data.f,1,itemtype = '2PL', TOL = .001)
coef <- data.frame(coef(mirt,simplify=TRUE,IRTpars=TRUE,na.rm=TRUE)$items)

knitr::kable(coef[,1:2])
plot(mirt.2PL, type = 'trace')
```

